lpbot: getdate.h File Reference
getdate.h File Reference
#include <sys/types.h>
#include <time.h>
Functions
time_t get_date (const char *p, const time_t *now)
Function Documentation
time_t get_date (const char * p, const time_t * now)
Definition at line 2238 of file getdate.c.
References EPOCH_YEAR, gmtime(), localtime(), MER24, mktime(), tLOCAL_ZONE, tm_diff(), TM_YEAR_BASE, to_hour(), to_year(), and yyparse().
Referenced by check_rss().