lpbot: getdate.c File Reference
getdate.c File Reference
#include <alloca.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include "getdate.h"
Data Structures
struct textint
struct table
struct parser_control
union YYSTYPE
union yyalloc
Defines
#define YYBISON 1
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 1
#define YYLSP_NEEDED 0
#define tAGO 258
#define tDST 259
#define tDAY 260
#define tDAY_UNIT 261
#define tDAYZONE 262
#define tHOUR_UNIT 263
#define tLOCAL_ZONE 264
#define tMERIDIAN 265
#define tMINUTE_UNIT 266
#define tMONTH 267
#define tMONTH_UNIT 268
#define tSEC_UNIT 269
#define tYEAR_UNIT 270
#define tZONE 271
#define tSNUMBER 272
#define tUNUMBER 273
#define IN_CTYPE_DOMAIN(c) 1
#define ISSPACE(c) (IN_CTYPE_DOMAIN (c) && isspace (c))
#define ISALPHA(c) (IN_CTYPE_DOMAIN (c) && isalpha (c))
#define ISLOWER(c) (IN_CTYPE_DOMAIN (c) && islower (c))
#define ISDIGIT_LOCALE(c) (IN_CTYPE_DOMAIN (c) && isdigit (c))
#define ISDIGIT(c) ((unsigned) (c) - '0' <= 9)
#define __attribute__(x)
#define ATTRIBUTE_UNUSED __attribute__ ((__unused__))
#define EPOCH_YEAR 1970
#define TM_YEAR_BASE 1900
#define HOUR(x) ((x) * 60)
#define PC (* (parser_control *) parm)
#define YYLEX_PARAM parm
#define YYPARSE_PARAM parm
#define YYDEBUG 0
#define YYERROR_VERBOSE 0
#define yystype YYSTYPE
#define YYSTYPE_IS_DECLARED 1
#define YYSTYPE_IS_TRIVIAL 1
#define YYSTACK_ALLOC malloc
#define YYSTACK_FREE free
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY(To, From, Count)
#define YYSTACK_RELOCATE(Stack)
#define YYFINAL 2
#define YYLAST 55
#define YYNTOKENS 22
#define YYNNTS 12
#define YYNRULES 55
#define YYNSTATES 66
#define YYUNDEFTOK 2
#define YYMAXUTOK 273
#define YYTRANSLATE(YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYPACT_NINF -17
#define YYTABLE_NINF -1
#define YYSIZE_T unsigned int
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrlab1
#define YYFAIL goto yyerrlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYTERROR 1
#define YYERRCODE 256
#define YYLLOC_DEFAULT(Current, Rhs, N)
#define YYLEX yylex (&yylval, YYLEX_PARAM)
#define YYDPRINTF(Args)
#define YYDSYMPRINT(Args)
#define YYDSYMPRINTF(Title, Token, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYPOPSTACK (yyvsp--, yyssp--)
Typedefs
typedef short yysigned_char
Enumerations
enum yytokentype {
tAGO = 258, tDST = 259, tDAY = 260, tDAY_UNIT = 261,
tDAYZONE = 262, tHOUR_UNIT = 263, tLOCAL_ZONE = 264, tMERIDIAN = 265,
tMINUTE_UNIT = 266, tMONTH = 267, tMONTH_UNIT = 268, tSEC_UNIT = 269,
tYEAR_UNIT = 270, tZONE = 271, tSNUMBER = 272, tUNUMBER = 273
}
enum { MERam, MERpm, MER24 }
Functions
static int yyerror ()
static int yylex ()
static void yydestruct (int yytype, YYSTYPE *yyvaluep)
int yyparse ()
int yyparse (void *YYPARSE_PARAM)
struct tm * gmtime ()
struct tm * localtime ()
time_t mktime ()
static int to_hour (int hours, int meridian)
static int to_year (textint textyear)
static table const * lookup_zone (parser_control const *pc, char const *name)
static int tm_diff (struct tm const *a, struct tm const *b)
static table const * lookup_word (parser_control const *pc, char *word)
static int yylex (YYSTYPE *lvalp, parser_control *pc)
static int yyerror (char *s ATTRIBUTE_UNUSED)
time_t get_date (const char *p, const time_t *now)
Variables
static const unsigned char yytranslate []
static const unsigned char yyr1 []
static const unsigned char yyr2 []
static const unsigned char yydefact []
static const yysigned_char yydefgoto []
static const yysigned_char yypact []
static const yysigned_char yypgoto []
static const unsigned char yytable []
static const yysigned_char yycheck []
static const unsigned char yystos []
static table const meridian_table []
static table const dst_table []
static table const month_and_day_table []
static table const time_units_table []
static table const relative_time_table []
static table const time_zone_table []
static table const military_table []
Define Documentation
#define __attribute__ (x)
Definition at line 165 of file getdate.c.
#define ATTRIBUTE_UNUSED __attribute__ ((__unused__))
Definition at line 169 of file getdate.c.
#define EPOCH_YEAR 1970
Definition at line 172 of file getdate.c.
Referenced by get_date().
#define HOUR (x) ((x) * 60)
Definition at line 175 of file getdate.c.
#define IN_CTYPE_DOMAIN (c) 1
Definition at line 144 of file getdate.c.
#define ISALPHA (c) (IN_CTYPE_DOMAIN (c) && isalpha (c))
Definition at line 149 of file getdate.c.
Referenced by yylex().
#define ISDIGIT (c) ((unsigned) (c) - '0' <= 9)
Definition at line 160 of file getdate.c.
Referenced by yylex().
#define ISDIGIT_LOCALE (c) (IN_CTYPE_DOMAIN (c) && isdigit (c))
Definition at line 151 of file getdate.c.
#define ISLOWER (c) (IN_CTYPE_DOMAIN (c) && islower (c))
Definition at line 150 of file getdate.c.
Referenced by lookup_word().
#define ISSPACE (c) (IN_CTYPE_DOMAIN (c) && isspace (c))
Definition at line 148 of file getdate.c.
Referenced by yylex().
#define PC (* (parser_control *) parm)
Definition at line 245 of file getdate.c.
Referenced by yyparse().
#define tAGO 258
Definition at line 74 of file getdate.c.
#define tDAY 260
Definition at line 76 of file getdate.c.
#define tDAY_UNIT 261
Definition at line 77 of file getdate.c.
#define tDAYZONE 262
Definition at line 78 of file getdate.c.
#define tDST 259
Definition at line 75 of file getdate.c.
#define tHOUR_UNIT 263
Definition at line 79 of file getdate.c.
#define tLOCAL_ZONE 264
Definition at line 80 of file getdate.c.
Referenced by get_date().
#define TM_YEAR_BASE 1900
Definition at line 173 of file getdate.c.
Referenced by get_date(), and tm_diff().
#define tMERIDIAN 265
Definition at line 81 of file getdate.c.
#define tMINUTE_UNIT 266
Definition at line 82 of file getdate.c.
#define tMONTH 267
Definition at line 83 of file getdate.c.
#define tMONTH_UNIT 268
Definition at line 84 of file getdate.c.
#define tSEC_UNIT 269
Definition at line 85 of file getdate.c.
#define tSNUMBER 272
Definition at line 88 of file getdate.c.
Referenced by yylex().
#define tUNUMBER 273
Definition at line 89 of file getdate.c.
Referenced by yylex().
#define tYEAR_UNIT 270
Definition at line 86 of file getdate.c.
#define tZONE 271
Definition at line 87 of file getdate.c.
#define YY_REDUCE_PRINT (Rule)
Definition at line 770 of file getdate.c.
Referenced by yyparse().
#define YY_STACK_PRINT (Bottom, Top)
Definition at line 769 of file getdate.c.
#define YYABORT goto yyabortlab
Definition at line 627 of file getdate.c.
Referenced by yyparse().
#define YYACCEPT goto yyacceptlab
Definition at line 626 of file getdate.c.
Referenced by yyparse().
#define YYBACKUP (Token, Value)
Value:
do                                                              \
  if (yychar == YYEMPTY && yylen == 1)                          \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      yytoken = YYTRANSLATE (yychar);                           \
      YYPOPSTACK;                                               \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror ("syntax error: cannot back up");\
      YYERROR;                                                  \
    }                                                           \
while (0)
Definition at line 639 of file getdate.c.
#define YYBISON 1
Definition at line 37 of file getdate.c.
#define yyclearin (yychar = YYEMPTY)
Definition at line 622 of file getdate.c.
#define YYCOPY (To, From, Count)
Value:
do                                      \
        {                                       \
          register YYSIZE_T yyi;                \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (To)[yyi] = (From)[yyi];            \
        }                                       \
      while (0)
Definition at line 347 of file getdate.c.
#define YYDEBUG 0
Definition at line 256 of file getdate.c.
#define YYDPRINTF (Args)
Definition at line 766 of file getdate.c.
Referenced by yyparse().
#define YYDSYMPRINT (Args)
Definition at line 767 of file getdate.c.
#define YYDSYMPRINTF (Title, Token, Value, Location)
Definition at line 768 of file getdate.c.
Referenced by yyparse().
#define YYEMPTY (-2)
Definition at line 623 of file getdate.c.
Referenced by yyparse().
#define YYEOF 0
Definition at line 624 of file getdate.c.
Referenced by yyparse().
#define YYERRCODE 256
Definition at line 657 of file getdate.c.
#define yyerrok (yyerrstatus = 0)
Definition at line 621 of file getdate.c.
#define YYERROR goto yyerrlab1
Definition at line 628 of file getdate.c.
#define YYERROR_VERBOSE 0
Definition at line 264 of file getdate.c.
#define YYFAIL goto yyerrlab
Definition at line 635 of file getdate.c.
#define YYFINAL 2
Definition at line 383 of file getdate.c.
Referenced by yyparse().
#define YYINITDEPTH 200
Definition at line 776 of file getdate.c.
Referenced by yyparse().
#define YYLAST 55
Definition at line 385 of file getdate.c.
Referenced by yyparse().
#define YYLEX yylex (&yylval, YYLEX_PARAM)
Definition at line 673 of file getdate.c.
Referenced by yyparse().
#define YYLEX_PARAM parm
Definition at line 246 of file getdate.c.
#define YYLLOC_DEFAULT (Current, Rhs, N)
Value:
Current.first_line   = Rhs[1].first_line;      \
  Current.first_column = Rhs[1].first_column;    \
  Current.last_line    = Rhs[N].last_line;       \
  Current.last_column  = Rhs[N].last_column;
Definition at line 663 of file getdate.c.
#define YYLSP_NEEDED 0
Definition at line 46 of file getdate.c.
#define YYMAXDEPTH 10000
Definition at line 791 of file getdate.c.
Referenced by yyparse().
#define YYMAXUTOK 273
Definition at line 398 of file getdate.c.
#define YYNNTS 12
Definition at line 390 of file getdate.c.
#define YYNRULES 55
Definition at line 392 of file getdate.c.
#define YYNSTATES 66
Definition at line 394 of file getdate.c.
#define YYNTOKENS 22
Definition at line 388 of file getdate.c.
#define YYPACT_NINF -17
Definition at line 548 of file getdate.c.
Referenced by yyparse().
#define YYPARSE_PARAM parm
Definition at line 247 of file getdate.c.
#define YYPOPSTACK (yyvsp--, yyssp--)
#define YYPURE 1
Definition at line 43 of file getdate.c.
#define YYRECOVERING () (!!yyerrstatus)
Definition at line 637 of file getdate.c.
#define YYSIZE_T unsigned int
Definition at line 618 of file getdate.c.
Referenced by yyparse().
#define YYSKELETON_NAME "yacc.c"
Definition at line 40 of file getdate.c.
#define YYSTACK_ALLOC malloc
Definition at line 314 of file getdate.c.
Referenced by yyparse().
#define YYSTACK_BYTES (N)
Value:
((N) * (sizeof (short) + sizeof (YYSTYPE))                              \
      + YYSTACK_GAP_MAXIMUM)
Definition at line 336 of file getdate.c.
Referenced by yyparse().
#define YYSTACK_FREE free
Definition at line 315 of file getdate.c.
Referenced by yyparse().
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
Definition at line 332 of file getdate.c.
#define YYSTACK_RELOCATE (Stack)
Value:
do                                                                      \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack, Stack, yysize);                          \
        Stack = &yyptr->Stack;                                          \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (0)
Definition at line 363 of file getdate.c.
Referenced by yyparse().
#define yystype YYSTYPE
Definition at line 275 of file getdate.c.
#define YYSTYPE_IS_DECLARED 1
Definition at line 276 of file getdate.c.
#define YYSTYPE_IS_TRIVIAL 1
Definition at line 277 of file getdate.c.
#define YYTABLE_NINF -1
Definition at line 571 of file getdate.c.
Referenced by yyparse().
#define YYTERROR 1
Definition at line 656 of file getdate.c.
#define YYTRANSLATE (YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Definition at line 400 of file getdate.c.
Referenced by yyparse().
#define YYUNDEFTOK 2
Definition at line 397 of file getdate.c.
Typedef Documentation
typedef short yysigned_char
Definition at line 379 of file getdate.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
MERam
MERpm
MER24
Definition at line 194 of file getdate.c.
enum yytokentype
Enumerator:
tAGO
tDST
tDAY
tDAY_UNIT
tDAYZONE
tHOUR_UNIT
tLOCAL_ZONE
tMERIDIAN
tMINUTE_UNIT
tMONTH
tMONTH_UNIT
tSEC_UNIT
tYEAR_UNIT
tZONE
tSNUMBER
tUNUMBER
Definition at line 55 of file getdate.c.
Function Documentation
time_t get_date (const char * p, const time_t * now)
Definition at line 2238 of file getdate.c.
References EPOCH_YEAR, gmtime(), localtime(), MER24, mktime(), tLOCAL_ZONE, tm_diff(), TM_YEAR_BASE, to_hour(), to_year(), and yyparse().
Referenced by check_rss().
struct tm* gmtime () [read]
Referenced by get_date().
struct tm* localtime () [read]
Referenced by get_date().
static table const* lookup_word (parser_control const * pc, char * word) [static]
Definition at line 2079 of file getdate.c.
References ISLOWER, lookup_zone(), and table::name.
Referenced by yylex().
static table const* lookup_zone (parser_control const * pc, char const * name) [static]
Definition at line 2035 of file getdate.c.
References parser_control::local_time_zone_table, and table::name.
Referenced by lookup_word().
time_t mktime ()
Referenced by get_date().
static int tm_diff (struct tm const * a, struct tm const * b) [static]
Definition at line 2057 of file getdate.c.
References TM_YEAR_BASE.
Referenced by get_date().
static int to_hour (int hours, int meridian) [static]
Definition at line 2002 of file getdate.c.
References MER24, MERam, and MERpm.
Referenced by get_date().
static int to_year (textint textyear) [static]
Definition at line 2019 of file getdate.c.
References textint::digits, and textint::value.
Referenced by get_date().
static void yydestruct (int yytype, YYSTYPE * yyvaluep) [static]
Definition at line 895 of file getdate.c.
static int yyerror (char *s ATTRIBUTE_UNUSED) [static]
Definition at line 2228 of file getdate.c.
static int yyerror () [static]
static int yylex (YYSTYPE * lvalp, parser_control * pc) [static]
Definition at line 2148 of file getdate.c.
References textint::digits, parser_control::input, YYSTYPE::intval, ISALPHA, ISDIGIT, ISSPACE, lookup_word(), YYSTYPE::textintval, tSNUMBER, tUNUMBER, table::type, table::value, and textint::value.
static int yylex () [static]
int yyparse (void * YYPARSE_PARAM)
Definition at line 940 of file getdate.c.
References textint::digits, YYSTYPE::intval, MER24, PC, YYSTYPE::textintval, textint::value, YY_REDUCE_PRINT, YYABORT, YYACCEPT, yycheck, yydefact, YYDPRINTF, YYDSYMPRINTF, YYEMPTY, YYEOF, YYFINAL, YYINITDEPTH, YYLAST, YYLEX, YYMAXDEPTH, yypact, YYPACT_NINF, yyr2, YYSIZE_T, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yytable, YYTABLE_NINF, and YYTRANSLATE.
int yyparse ()
Referenced by get_date().
Variable Documentation
table const dst_table[] [static]
Initial value:
{
  { "DST", tDST, 0 }
}
Definition at line 1833 of file getdate.c.
table const meridian_table[] [static]
Initial value:
{
  { "AM",   tMERIDIAN, MERam },
  { "A.M.", tMERIDIAN, MERam },
  { "PM",   tMERIDIAN, MERpm },
  { "P.M.", tMERIDIAN, MERpm },
  { 0, 0, 0 }
}
Definition at line 1824 of file getdate.c.
table const military_table[] [static]
Initial value:
{
  { "A", tZONE, -HOUR ( 1) },
  { "B", tZONE, -HOUR ( 2) },
  { "C", tZONE, -HOUR ( 3) },
  { "D", tZONE, -HOUR ( 4) },
  { "E", tZONE, -HOUR ( 5) },
  { "F", tZONE, -HOUR ( 6) },
  { "G", tZONE, -HOUR ( 7) },
  { "H", tZONE, -HOUR ( 8) },
  { "I", tZONE, -HOUR ( 9) },
  { "K", tZONE, -HOUR (10) },
  { "L", tZONE, -HOUR (11) },
  { "M", tZONE, -HOUR (12) },
  { "N", tZONE,  HOUR ( 1) },
  { "O", tZONE,  HOUR ( 2) },
  { "P", tZONE,  HOUR ( 3) },
  { "Q", tZONE,  HOUR ( 4) },
  { "R", tZONE,  HOUR ( 5) },
  { "S", tZONE,  HOUR ( 6) },
  { "T", tZONE,  HOUR ( 7) },
  { "U", tZONE,  HOUR ( 8) },
  { "V", tZONE,  HOUR ( 9) },
  { "W", tZONE,  HOUR (10) },
  { "X", tZONE,  HOUR (11) },
  { "Y", tZONE,  HOUR (12) },
  { "Z", tZONE,  HOUR ( 0) },
  { 0, 0, 0 }
}
Definition at line 1969 of file getdate.c.
table const month_and_day_table[] [static]
Initial value:
{
  { "JANUARY",  tMONTH,  1 },
  { "FEBRUARY", tMONTH,  2 },
  { "MARCH",    tMONTH,  3 },
  { "APRIL",    tMONTH,  4 },
  { "MAY",      tMONTH,  5 },
  { "JUNE",     tMONTH,  6 },
  { "JULY",     tMONTH,  7 },
  { "AUGUST",   tMONTH,  8 },
  { "SEPTEMBER",tMONTH,  9 },
  { "SEPT",     tMONTH,  9 },
  { "OCTOBER",  tMONTH, 10 },
  { "NOVEMBER", tMONTH, 11 },
  { "DECEMBER", tMONTH, 12 },
  { "SUNDAY",   tDAY,    0 },
  { "MONDAY",   tDAY,    1 },
  { "TUESDAY",  tDAY,    2 },
  { "TUES",     tDAY,    2 },
  { "WEDNESDAY",tDAY,    3 },
  { "WEDNES",   tDAY,    3 },
  { "THURSDAY", tDAY,    4 },
  { "THUR",     tDAY,    4 },
  { "THURS",    tDAY,    4 },
  { "FRIDAY",   tDAY,    5 },
  { "SATURDAY", tDAY,    6 },
  { 0, 0, 0 }
}
Definition at line 1838 of file getdate.c.
table const relative_time_table[] [static]
Initial value:
{
  { "TOMORROW", tDAY_UNIT,       1 },
  { "YESTERDAY",tDAY_UNIT,      -1 },
  { "TODAY",    tDAY_UNIT,       0 },
  { "NOW",      tDAY_UNIT,       0 },
  { "LAST",     tUNUMBER,       -1 },
  { "THIS",     tUNUMBER,        0 },
  { "NEXT",     tUNUMBER,        1 },
  { "FIRST",    tUNUMBER,        1 },
  { "THIRD",    tUNUMBER,        3 },
  { "FOURTH",   tUNUMBER,        4 },
  { "FIFTH",    tUNUMBER,        5 },
  { "SIXTH",    tUNUMBER,        6 },
  { "SEVENTH",  tUNUMBER,        7 },
  { "EIGHTH",   tUNUMBER,        8 },
  { "NINTH",    tUNUMBER,        9 },
  { "TENTH",    tUNUMBER,       10 },
  { "ELEVENTH", tUNUMBER,       11 },
  { "TWELFTH",  tUNUMBER,       12 },
  { "AGO",      tAGO,            1 },
  { 0, 0, 0 }
}
Definition at line 1883 of file getdate.c.
table const time_units_table[] [static]
Initial value:
{
  { "YEAR",     tYEAR_UNIT,      1 },
  { "MONTH",    tMONTH_UNIT,     1 },
  { "FORTNIGHT",tDAY_UNIT,      14 },
  { "WEEK",     tDAY_UNIT,       7 },
  { "DAY",      tDAY_UNIT,       1 },
  { "HOUR",     tHOUR_UNIT,      1 },
  { "MINUTE",   tMINUTE_UNIT,    1 },
  { "MIN",      tMINUTE_UNIT,    1 },
  { "SECOND",   tSEC_UNIT,       1 },
  { "SEC",      tSEC_UNIT,       1 },
  { 0, 0, 0 }
}
Definition at line 1867 of file getdate.c.
table const time_zone_table[] [static]
Definition at line 1913 of file getdate.c.
const yysigned_char yycheck[] [static]
Initial value:
{
       0,    17,    18,    10,    17,     5,     6,     7,     8,     9,
      17,    11,    12,    13,    14,    15,    16,    17,    18,     5,
       6,    20,     8,     4,    10,    11,    12,    13,    14,    15,
       3,    17,     6,    19,     8,    21,     4,    11,    10,    13,
      14,    15,    17,    18,    20,    17,    17,    19,    18,    18,
      62,    18,    -1,    18,    18,    21
}
Definition at line 582 of file getdate.c.
Referenced by yyparse().
const unsigned char yydefact[] [static]
Initial value:
{
       2,     0,     1,    21,    43,    19,    46,    16,    49,     0,
      40,    52,    37,    18,     0,    53,     3,     4,     5,     6,
       8,     7,     9,    34,    10,    22,    17,     0,    29,    20,
      42,    45,    48,    39,    51,    36,    23,    41,    44,    11,
      47,    31,    38,    50,    35,     0,     0,     0,    33,    28,
       0,    27,    32,    26,    54,    24,    30,    55,    13,     0,
      12,     0,    54,    25,    15,    14
}
Definition at line 528 of file getdate.c.
Referenced by yyparse().
const yysigned_char yydefgoto[] [static]
Initial value:
{
      -1,     1,    16,    17,    18,    19,    20,    21,    22,    23,
      24,    60
}
Definition at line 540 of file getdate.c.
const yysigned_char yypact[] [static]
Initial value:
{
     -17,     0,   -17,     1,   -17,   -17,   -17,    19,   -17,   -16,
     -17,   -17,   -17,    32,    26,    14,   -17,   -17,   -17,   -17,
     -17,   -17,   -17,    27,   -17,   -17,   -17,   -13,    24,   -17,
     -17,   -17,   -17,   -17,   -17,   -17,   -17,   -17,   -17,   -17,
     -17,    25,   -17,   -17,   -17,    29,    30,    31,   -17,   -17,
      33,   -17,   -17,   -17,    28,    34,   -17,   -17,   -17,    35,
     -17,    36,    -7,   -17,   -17,   -17
}
Definition at line 549 of file getdate.c.
Referenced by yyparse().
const yysigned_char yypgoto[] [static]
Initial value:
{
     -17,   -17,   -17,   -17,   -17,   -17,   -17,   -17,   -17,   -17,
     -17,   -12
}
Definition at line 561 of file getdate.c.
const unsigned char yyr1[] [static]
Initial value:
{
       0,    22,    23,    23,    24,    24,    24,    24,    24,    24,
      24,    25,    25,    25,    25,    25,    26,    26,    27,    27,
      27,    28,    28,    28,    29,    29,    29,    29,    29,    29,
      29,    29,    29,    30,    30,    31,    31,    31,    31,    31,
      31,    31,    31,    31,    31,    31,    31,    31,    31,    31,
      31,    31,    31,    32,    33,    33
}
Definition at line 504 of file getdate.c.
const unsigned char yyr2[] [static]
Initial value:
{
       0,     2,     0,     2,     1,     1,     1,     1,     1,     1,
       1,     2,     4,     4,     6,     6,     1,     2,     1,     1,
       2,     1,     2,     2,     3,     5,     3,     3,     3,     2,
       4,     2,     3,     2,     1,     2,     2,     1,     2,     2,
       1,     2,     2,     1,     2,     2,     1,     2,     2,     1,
       2,     2,     1,     1,     0,     1
}
Definition at line 515 of file getdate.c.
Referenced by yyparse().
const unsigned char yystos[] [static]
Initial value:
{
       0,    23,     0,     5,     6,     7,     8,     9,    11,    12,
      13,    14,    15,    16,    17,    18,    24,    25,    26,    27,
      28,    29,    30,    31,    32,    20,     4,    17,    18,     4,
       6,     8,    11,    13,    14,    15,     5,     6,     8,    10,
      11,    12,    13,    14,    15,    17,    19,    21,     3,    17,
      20,    17,    18,    17,    18,    18,    18,    10,    17,    19,
      33,    21,    18,    18,    17,    33
}
Definition at line 594 of file getdate.c.
const unsigned char yytable[] [static]
Initial value:
{
       2,    27,    28,    57,    49,     3,     4,     5,     6,     7,
      64,     8,     9,    10,    11,    12,    13,    14,    15,    36,
      37,    25,    38,    26,    39,    40,    41,    42,    43,    44,
      48,    45,    30,    46,    31,    47,    29,    32,    57,    33,
      34,    35,    51,    52,    50,    58,    53,    59,    54,    55,
      65,    56,     0,    62,    63,    61
}
Definition at line 572 of file getdate.c.
Referenced by yyparse().
const unsigned char yytranslate[] [static]
Definition at line 404 of file getdate.c.