lpbot: Handling or servers
Handling or servers
Functions
lp_server * lp_find_server (char *chatname)
int parseServer (xmlDoc *doc, xmlNode *cur)
void lp_server_free (lp_server *srv)
Function Documentation
lp_server* lp_find_server (char * chatname)
Searches for a user
Parameters:
chatname the id of the server
Returns:
the server pointer on success, NULL on error
Definition at line 17 of file servers.c.
References __lp_server::chatname, config, server, and __lp_config::servers.
Referenced by parseRss().
void lp_server_free (lp_server * srv)
Frees a server.
Parameters:
srv the server to free
Definition at line 69 of file servers.c.
References __lp_server::address, __lp_server::channels, __lp_server::chatname, __lp_server::nick, __lp_server::realname, and __lp_server::username.
Referenced by lp_config_free().
int parseServer (xmlDoc * doc, xmlNode * cur)
Parses an entry of a server in the config
Parameters:
doc the xml document
cur the current xml node
Returns:
0 on success, -1 on failure
Definition at line 35 of file servers.c.
References __lp_server::address, __lp_server::channels, __lp_server::chatname, config, __lp_server::nick, __lp_server::port, __lp_server::realname, server, __lp_config::servers, and __lp_server::username.
Referenced by parseConfig().