lpbot: Database handling
Database handling
Functions
static lp_record_ver * parseVersion (xmlDoc *doc, xmlNode *cur)
static int parseRecord (xmlDoc *doc, xmlNode *cur)
int parseRecords (char *docname)
int saveRecords (char *docname)
void lp_record_free (lp_record *rec)
void lp_record_ver_free (lp_record_ver *ver)
Function Documentation
void lp_record_free (lp_record * rec)
Frees a record.
Parameters:
rec the record to free
Definition at line 159 of file db.c.
References lp_record_ver_free(), __lp_record::name, and __lp_record::versions.
Referenced by lp_config_free().
void lp_record_ver_free (lp_record_ver * ver)
Frees a record version.
Parameters:
ver the record version to free
Definition at line 171 of file db.c.
References __lp_record_ver::author, and __lp_record_ver::content.
Referenced by lp_record_free().
static int parseRecord (xmlDoc * doc, xmlNode * cur) [static]
Parses a given record of the database
Parameters:
doc the xml document
cur the current xml node
Returns:
0 on success, -1 on failure
Definition at line 45 of file db.c.
References config, __lp_record::name, parseVersion(), __lp_config::records, and __lp_record::versions.
Referenced by parseRecords().
int parseRecords (char * docname)
Parses the database file of the bot.
Parameters:
docname the filename of the db xml
Returns:
0 on success, -1 on failure
Definition at line 69 of file db.c.
References parseRecord().
Referenced by main().
static lp_record_ver* parseVersion (xmlDoc * doc, xmlNode * cur) [static]
Parses a given version of a database record
Parameters:
doc the xml document
cur the current xml node
Returns:
0 on success, -1 on failure
Definition at line 19 of file db.c.
References __lp_record_ver::author, __lp_record_ver::content, and __lp_record_ver::date.
Referenced by parseRecord().
int saveRecords (char * docname)
Writes the database of the bot to a file.
Parameters:
docname the filename of the db xml
Returns:
0 on success, -1 on failure
Definition at line 117 of file db.c.
References __lp_record_ver::author, config, __lp_record_ver::content, __lp_record_ver::date, __lp_record::name, __lp_config::records, and __lp_record::versions.
Referenced by lp_handle_command().