lpbot: The password reminder
The password reminder
Functions
int remind (lp_user *user)
Function Documentation
int remind (lp_user * user)
Sends a password reminder to a given user.
Parameters:
user the user pointer
Returns:
0 on success, -1 on error
Definition at line 21 of file remind.c.
References __lp_user::email, lp_create_sock(), lp_resolve(), lp_send(), __lp_user::pass, and server.
Referenced by lp_handle_command().