lpbot: The IRC bot
The IRC bot
Functions
int main ()
Function Documentation
int main ()
The main function of the bot
Returns:
0 on success, -1 on error
Definition at line 10 of file lpbot.c.
References config, lp_check_rss(), lp_config_free(), lp_connect(), lp_serve(), parseConfig(), parseRecords(), __lp_config::rss_interval, and __lp_config::servers.