lpbot: The bot controller
The bot controller
Functions
int srv_handler (GIOChannel *source, GIOCondition condition, gpointer data)
int kbd_handler (GIOChannel *source, GIOCondition condition, gpointer data)
int main (int argv, char **argc)
Function Documentation
int kbd_handler (GIOChannel * source, GIOCondition condition, gpointer data)
Handles the input from the standard input
Parameters:
source not used
condition not used
data not used
Returns:
TRUE on success, FALSE on error
Definition at line 65 of file lpbotctl.c.
References IRC_LINE_LENGHT, lp_send(), __lp_server::sock, and sockerr_again.
Referenced by main().
int main (int argv, char ** argc)
The main function of the control client.
Parameters:
argv number of parameters
argc the parameters
Returns:
0 on success, -1 on error
Definition at line 92 of file lpbotctl.c.
References __lp_server::address, __lp_server::chan, kbd_handler(), lp_connect(), LP_HOST, LP_PORT, __lp_server::port, __lp_server::sock, and srv_handler().
int srv_handler (GIOChannel * source, GIOCondition condition, gpointer data)
Handles the incoming messages from the server
Parameters:
source not used
condition not used
data not used
Returns:
TRUE on success, FALSE on error
Definition at line 31 of file lpbotctl.c.
References IRC_LINE_LENGHT, __lp_server::sock, and sockerr_again.
Referenced by main().