lpbot: The RSS parser
The RSS parser
Functions
int parseRss (xmlDoc *doc, xmlNode *cur)
int check_rss (lp_rss *rss)
void lp_rss_free (lp_rss *rss)
Function Documentation
int check_rss (lp_rss * rss)
Definition at line 48 of file rss.c.
References __lp_rss::channel, get_date(), __lp_rss::lastupd, lp_send(), __lp_rss::name, __lp_rss::server, and __lp_rss::url.
Referenced by lp_check_rss().
void lp_rss_free (lp_rss * rss)
Frees an rss feed.
Parameters:
rss the rss feed to free
Definition at line 81 of file rss.c.
References __lp_rss::channel, __lp_rss::name, and __lp_rss::url.
Referenced by lp_config_free().
int parseRss (xmlDoc * doc, xmlNode * cur)
Parses the RSS part of the configuration file.
Parameters:
doc the xml document
cur the current xml node
Returns:
0 on success, -1 on failure
Definition at line 18 of file rss.c.
References __lp_rss::channel, config, lp_find_server(), __lp_rss::name, __lp_config::rsslist, __lp_rss::server, and __lp_rss::url.
Referenced by parseConfig().