lpbot: Configuration file
Configuration file
Functions
static int parseOptions (xmlDoc *doc, xmlNode *cur)
int parseConfig (char *docname)
void lp_config_free (lp_config *cfg)
Function Documentation
void lp_config_free (lp_config * cfg)
Frees a config ptr.
Parameters:
cfg the config ptr
Definition at line 107 of file config.c.
References __lp_config::ident_to, lp_record_free(), lp_rss_free(), lp_server_free(), lp_user_free(), __lp_config::records, __lp_config::rsslist, __lp_config::servers, and __lp_config::users.
Referenced by main().
int parseConfig (char * docname)
Parses the configuration file of the bot.
Parameters:
docname the filename of the config xml
Returns:
0 on success, -1 on failure
Definition at line 44 of file config.c.
References parseOptions(), parseRss(), parseServer(), and parseUser().
Referenced by main().
static int parseOptions (xmlDoc * doc, xmlNode * cur) [static]
Parses the general options of the bot.
Parameters:
doc the xml document
cur the current xml node
Returns:
0 on success, -1 on failure
Definition at line 17 of file config.c.
References config, __lp_config::ident_method, LP_IDENT_PASS, LP_IDENT_SERVICES, and __lp_config::rss_interval.
Referenced by parseConfig().